import type { Metadata } from "next";
import NavBar from "@/components/Nav";
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="container mx-auto h-screen flex flex-col justify-between pb-5">
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
